/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper */

#ifndef _Included_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
#define _Included_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    runScript
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_runScript
  (JNIEnv *, jobject, jstring);

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    checkService
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_checkService
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    checkPlugin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_checkPlugin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    getLibraryOutput
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_getLibraryOutput
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fi_helsinki_cs_iot_hub_jsengine_DuktapeJavascriptEngineWrapper_run
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
